# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JN4qr0IPYYfajCQN53Ke_kgkrB0uim8E
"""

!pip install durable_rules

from durable.lang import *

with ruleset('water_bath_rules'):
    # Rule 1
    @when_all((m.sample == 'TSSRD') | (m.sample == 'TSSRC') | (m.sample == 'TSSRB') | (m.sample == 'TSSA') | (m.sample == 'TSSR1') | (m.sample == 'TSSR0')
            | (m.sample == 'TSSR2') | (m.sample == 'TSSR3') | (m.sample == 'TSSR4') | (m.sample == 'TSSR5') | (m.sample == 'TSSR6') & (m.request_date == 7))
    def rule_1(c):
        water_bath = 43
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.13.")

    # Rule 2
    @when_all((m.sample == 'TSSR7') | (m.sample == 'TSSR8') & (m.request_date == 14))
    def rule_2(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.12.")
        
    # Rule 3
    @when_all(((m.sample == 'TSSLD') | (m.sample == 'TSSLC') | (m.sample == 'TSSLB') | (m.sample == 'TSSLA') | (m.sample == 'TSSL1') | (m.sample == 'TSSL0') 
         | (m.sample == 'TSSL2') | (m.sample == 'TSSL3') | (m.sample == 'TSSL4') | (m.sample == 'TSSL5') | (m.sample == 'TSSL6') | (m.sample == 'TSSL7') | (m.sample == 'TSSL8')) & (m.request_date == 14))
    def rule_3(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.1.")

    # Rule 4
    @when_all(((m.sample == 'TSSLD') | (m.sample == 'TSSLC') | (m.sample == 'TSSLB') | (m.sample == 'TSSLA') | (m.sample == 'TSSL1') | (m.sample == 'TSSL0') 
         | (m.sample == 'TSSL2') | (m.sample == 'TSSL3') | (m.sample == 'TSSL4') | (m.sample == 'TSSL5') | (m.sample == 'TSSL6') | (m.sample == 'TSSL7') | (m.sample == 'TSSL8')) & (m.request_date == 7) & (m.speed == 'fast'))
    def rule_4(c):
        water_bath = 43
        print(f"Putting {c.m.sample} in {c.m.speed} water bath {water_bath}°C no.15.")

    # Rule 5
    @when_all((m.sample == 'TSSQA') | (m.sample == 'TSSQ1') | (m.sample == 'TSSQ0') | (m.sample == 'TSSQ2') | (m.sample == 'TSSQ3') | (m.sample == 'TSSQ4') 
             | (m.sample == 'TSSQ5') | (m.sample == 'TSSQ6') | (m.sample == 'TSSQ7') | (m.sample == 'TSSQ8') & (m.request_date == 7))
    def rule_5(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.2.")

    # Rule 6
    @when_all((m.sample == 'TSSTD') | (m.sample == 'TSSTC') | (m.sample == 'TSSTB') | (m.sample == 'TSSTA') | (m.sample == 'TSST1') | (m.sample == 'TSST0') 
             | (m.sample == 'TSST2') | (m.sample == 'TSST3') | (m.sample == 'TSST4') | (m.sample == 'TSST5') | (m.sample == 'TSST6') & (m.request_date == 7))
    def rule_6(c):
        water_bath = 43
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.14.")

    # Rule 7
    @when_all((m.sample == 'TSST7') | (m.sample == 'TSST8') & (m.request_date == 14))
    def rule_7(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.12.")

    # Rule 8
    @when_all((m.sample == 'TSSUA') | (m.sample == 'TSSU1') | (m.sample == 'TSSU0') | (m.sample == 'TSSU2') | (m.sample == 'TSSU3') | (m.sample == 'TSSU4') 
             | (m.sample == 'TSSU5') | (m.sample == 'TSSU6') & (m.request_date == 14))
    def rule_8(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.3.")

    # Rule 9
    @when_all((m.sample == 'TSSPA') | (m.sample == 'TSSP1') | (m.sample == 'TSSP0') | (m.sample == 'TSSP2') | (m.sample == 'TSSP3') | (m.sample == 'TSSP4') 
             | (m.sample == 'TSSP5') | (m.sample == 'TSSP7') & (m.request_date == 14))
    def rule_9(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.4.")

    # Rule 10
    @when_all((m.sample == 'TSEUE') | (m.sample == 'TSEUD') | (m.sample == 'TSEUC') | (m.sample == 'TSEUB') | (m.sample == 'TSEUA') | (m.sample == 'TSEU1') 
             | (m.sample == 'TSEU0') | (m.sample == 'TSEU2') & (m.request_date == 14))
    def rule_10(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.5.")

    # Rule 11
    @when_all((m.sample == 'TSEEA') | (m.sample == 'TSEE1') & (m.request_date == 14))
    def rule_11(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.6.")

    # Rule 12
    @when_all(((m.sample == 'TSSDC') | (m.sample == 'TSSDB') | (m.sample == 'TSSDA') | (m.sample == 'TSSD1') | (m.sample == 'TSSD0') | (m.sample == 'TSSD2') 
         | (m.sample == 'TSSD3') | (m.sample == 'TSSD4') | (m.sample == 'TSSD5') | (m.sample == 'TSSD6') | (m.sample == 'TSSD7') | (m.sample == 'TSSDZ')
         | (m.sample == 'TSSWB') | (m.sample == 'TSSWA') | (m.sample == 'TSSW1') | (m.sample == 'TSSW0') | (m.sample == 'TSSW2') | (m.sample == 'TSSW3')
         | (m.sample == 'TSSW4') | (m.sample == 'TSSW5') | (m.sample == 'TSSW6') | (m.sample == 'TSSW7')) & (m.request_date == 14))
    def rule_12(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.7.")


    # Rule 13
    @when_all(((m.sample == 'TSSDC') | (m.sample == 'TSSDB') | (m.sample == 'TSSDA') | (m.sample == 'TSSD1') | (m.sample == 'TSSD0') | (m.sample == 'TSSD2') 
         | (m.sample == 'TSSD3') | (m.sample == 'TSSD4') | (m.sample == 'TSSD5') | (m.sample == 'TSSD6') | (m.sample == 'TSSD7') | (m.sample == 'TSSDZ')
         | (m.sample == 'TSSWB') | (m.sample == 'TSSWA') | (m.sample == 'TSSW1') | (m.sample == 'TSSW0') | (m.sample == 'TSSW2') | (m.sample == 'TSSW3')
         | (m.sample == 'TSSW4') | (m.sample == 'TSSW5') | (m.sample == 'TSSW6') | (m.sample == 'TSSW7')) & (m.request_date == 28))
    def rule_13(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.8.")


    # Rule 14
    @when_all(((m.sample == 'TSSMA') | (m.sample == 'TSSM1') | (m.sample == 'TSSM0') | (m.sample == 'TSSM2') | (m.sample == 'TSSM3') | (m.sample == 'TSSM4') 
             | (m.sample == 'TSSM5') | (m.sample == 'TSSM6')) & (m.request_date == 7))
    def rule_14(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.9.")

    # Rule 15
    @when_all(((m.sample == 'TSSMA') | (m.sample == 'TSSM1') | (m.sample == 'TSSM0') | (m.sample == 'TSSM2') | (m.sample == 'TSSM3') | (m.sample == 'TSSM4') 
             | (m.sample == 'TSSM5') | (m.sample == 'TSSM6')) & (m.request_date == 14))
    def rule_15(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.10.")


    # Rule 16
    @when_all((m.sample == 'TSSEC') | (m.sample == 'TSSEB') | (m.sample == 'TSSEA') | (m.sample == 'TSSE1') | (m.sample == 'TSSE0') | (m.sample == 'TSSE2') 
             | (m.sample == 'TSSE3') | (m.sample == 'TSSE4') | (m.sample == 'TSSE5') | (m.sample == 'TSSE6') | (m.sample == 'TSSE7') & (m.request_date == 14))
    def rule_16(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.11.")

    # Rule 17
    @when_all(((m.sample == 'TSSDC') | (m.sample == 'TSSDB') | (m.sample == 'TSSDA') | (m.sample == 'TSSD1') | (m.sample == 'TSSD0') | (m.sample == 'TSSD2') 
             | (m.sample == 'TSSD3') | (m.sample == 'TSSD4') | (m.sample == 'TSSD5') | (m.sample == 'TSSD6') | (m.sample == 'TSSD7') | (m.sample == 'TSSDZ')
             | (m.sample == 'TSSWB') | (m.sample == 'TSSWA') | (m.sample == 'TSSW1') | (m.sample == 'TSSW0') | (m.sample == 'TSSW2') | (m.sample == 'TSSW3')
             | (m.sample == 'TSSW4') | (m.sample == 'TSSW5') | (m.sample == 'TSSW6') | (m.sample == 'TSSW7')) & (m.request_date == 7) & (m.speed == 'fast'))
    def rule_17(c):
        water_bath = 43
        print(f"Putting {c.m.sample} in {c.m.speed} water bath {water_bath}°C no.16.")

    # Rule 18
    @when_all(((m.sample == 'TSSDC') | (m.sample == 'TSSDB') | (m.sample == 'TSSDA') | (m.sample == 'TSSD1') | (m.sample == 'TSSD0') | (m.sample == 'TSSD2') 
              | (m.sample == 'TSSD3') | (m.sample == 'TSSD4') | (m.sample == 'TSSD5') | (m.sample == 'TSSD6') | (m.sample == 'TSSD7') | (m.sample == 'TSSDZ')
              | (m.sample == 'TSSWB') | (m.sample == 'TSSWA') | (m.sample == 'TSSW1') | (m.sample == 'TSSW0') | (m.sample == 'TSSW2') | (m.sample == 'TSSW3')
              | (m.sample == 'TSSW4') | (m.sample == 'TSSW5') | (m.sample == 'TSSW6') | (m.sample == 'TSSW7')) & (m.request_date == "14") & (m.speed == 'fast'))
    def rule_18(c):
        water_bath = 43
        print(f"Putting {c.m.sample} in {c.m.speed} water bath {water_bath}°C no.17.")


    # Rule 19
    @when_all((m.sample == 'TEST37'))
    def rule19(c):
        water_bath = 37
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.18.")

    # Rule 20
    @when_all((m.sample == 'TEST43'))
    def rule19(c):
        water_bath = 43
        print(f"Putting {c.m.sample} in water bath {water_bath}°C no.19.")

post('water_bath_rules', {'sample': 'TSSR2', 'request_date': 7})
post('water_bath_rules', {'sample': 'TSSR7', 'request_date': 14})
post('water_bath_rules', {'sample': 'TSSLD', 'request_date': 14})

post('water_bath_rules', {'sample': 'TSSLD', 'speed': 'fast', 'request_date': 7})
post('water_bath_rules', {'sample': 'TSSQA', 'request_date': 7})
post('water_bath_rules', {'sample': 'TSSTD', 'request_date': 7})

post('water_bath_rules', {'sample': 'TSST7', 'request_date': 14})
post('water_bath_rules', {'sample': 'TSSUA', 'request_date': 14})
post('water_bath_rules', {'sample': 'TSSPA', 'request_date': 14})

post('water_bath_rules', {'sample': 'TSEUE', 'request_date': 14})
post('water_bath_rules', {'sample': 'TSEEA', 'request_date': 14})
post('water_bath_rules', {'sample': 'TSSDC', 'request_date': 14})

post('water_bath_rules', {'sample': 'TSSDC', 'request_date': 28})
post('water_bath_rules', {'sample': 'TSSMA', 'request_date': 7})
post('water_bath_rules', {'sample': 'TSSMA', 'request_date': 14})

post('water_bath_rules', {'sample': 'TSSEC', 'request_date': 14})
post('water_bath_rules', {'sample': 'TSSDC', 'speed': 'fast', 'request_date': 7})
post('water_bath_rules', {'sample': 'TSSDC', 'speed': 'fast', 'request_date': "14"})

post('water_bath_rules', {'sample': 'TEST37'})
post('water_bath_rules', {'sample': 'TEST43'})

